
.TH "ftdi-hd44780" 1
.SH NAME
ftdi-hd44780
.SH SYNOPSIS
ftdi-hd44780 [\fIOPTION\fR]...

.SH DESCRIPTION
Control HD44780 based character LCD displays through FTDI FTx232 chips in HD44780 4-bit mode.

-i, --interface=\fIID\fR
    ftdi chip interface: 0 for auto, 1 for FT232H, 1-2 for FT2232H and 1-4 for FT4232H.

-n, --no-reset
    do not reset display, usefull when display has already been initialized with previous command call and should not be cleared this time

-4, --d4=\fIPIN\fR
    default 0

-5, --d5=\fIPIN\fR
    default 1

-6, --d6=\fIPIN\fR
    default 2

-7, --d7=\fIPIN\fR
    default 3

-e, --en=\fIPIN\fR
    default 4

-r, --rw=\fIPIN\fR
    default 5

-s, --rs=\fIPIN\fR
    default 6
    
    set hd44780 data pin connections, ftdi dbus is 0-7, cbus is 8-15

-c, --clear
    clear display at start and move cursor to home

-m, --home
    move cursor to home

-l, --line=\fILINE\fR
    position cursor to start of given line (0-3)

-t, --text=\fITEXT\fR
    text to write to display

.SH AUTHOR
Antti Partanen <aehparta@iki.fi>
.SH BUGS
Report bugs to aehparta@iki.fi.
.SH "SEE ALSO"
