
.TH "ftdi-bitbang" 1
.SH NAME
ftdi-bitbang
.SH SYNOPSIS
ftdi-bitbang [\fIOPTION\fR]...

.SH DESCRIPTION
Bitbang control for FTDI FTx232 chips.

-i, --interface=\fIID\fR
    ftdi chip interface: 0 for auto, 1 for FT232H, 1-2 for FT2232H and 1-4 for FT4232H.

.SH AUTHOR
Antti Partanen <aehparta@iki.fi>
.SH BUGS
Report bugs to aehparta@iki.fi.
.SH "SEE ALSO"
